pipeline {
    agent any

    stages {
        stage('Java Compile') {
            steps {
                dir('./jenkins-resources/calculator'){
                    sh 'gradlew compileJava'
                }
            }
        }

        stage('Java Unit Tests') {
            steps {
                dir('./jenkins-resources/calculator'){
                    sh 'gradlew test'
                }
            }
        }
    }
}