version: '3.8'
services:
  repository:
    image: repository:1.0
    container_name: myrepository
    volumes:
      - db_data:/data/db
    restart: always
    networks:
      - lemoncode-challenge
  backend:
    image: backend:1.0
    container_name: mybackend
    ports:
      - "5000:80"
    restart: always
    networks:
      - lemoncode-challenge
    depends_on:
      - repository
  frontend:
    image: frontend:1.0
    container_name: myfrontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
networks:
  lemoncode-challenge:
    name: lemoncode-challenge
volumes:
  db_data:
    name: db_data
