services:
  docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    restart: unless-stopped
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-bootcamp-docker-certs:/certs/client
      - jenkins-bootcamp-data:/var/jenkins_home
    networks:
      - jenkins-bootcamp

  jenkins:
    image: jenkins-bootcamp-dockercli
    container_name: jenkins-dockercli
    restart: unless-stopped
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - jenkins-bootcamp-docker-certs:/certs/client:ro
      - jenkins-bootcamp-data:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - jenkins-bootcamp

volumes:
  jenkins-bootcamp-docker-certs:
  jenkins-bootcamp-data:

networks:
  jenkins-bootcamp: