apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: persistence-ss
spec:
  selector:
    matchLabels:
      app: persistence-pod
  serviceName: persistence-svc
  replicas: 1 
  template:
    metadata:
      labels:
        app: persistence-pod
    spec:
      containers:
        - name: persistence-container
          image: lemoncodersbc/lc-todo-monolith-psql:v5-2024
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: persistence-vct
              mountPath: /var/lib/postgresql/data
          envFrom:
          - configMapRef:
              name: db-cm
  volumeClaimTemplates:
    - metadata:
        name: persistence-vct
      spec:
        storageClassName: persistence-sc
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi