apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-pod
  template:
    metadata:
      labels:
        app: todo-app-pod
    spec:
      containers:
      - name: todo-app-container
        image: lemoncodersbc/lc-todo-monolith-db:v5-2024
        envFrom:
          - configMapRef:
              name: todo-app-cm
