apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: persistence-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Delete
volumeBindingMode: Immediate

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistence-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: persistence-sc
  hostPath:
    path: /data/persistence-pv/


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistence-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: persistence-sc


