name: CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Build
        working-directory: ./Module04_CI_CD/github_actions/hangman-front
        run: |
          npm ci
          npm run build --if-present
      - name: Upload dist folder artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist_folder
          path: Module04_CI_CD/github_actions/hangman-front/dist

  delivery:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download dist folder artifact
        uses: actions/download-artifact@v4
        with:
          name: dist_folder
          path: Module04_CI_CD/github_actions/hangman-front/dist
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Docker builder
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./Module04_CI_CD/github_actions/hangman-front
          push: true
          tags: ${{ github.actor }}/hangman-front-actions-2024:latest
          file: ./Module04_CI_CD/github_actions/hangman-front/Dockerfile.workflow
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}