name: E2E

on:
  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v4
    #   - name: Setup Node.js version
    #     uses: actions/setup-node@v4
    #     with:
    #       node-version: 16
    #   - name: Install dependencies
    #     working-directory: ./Module04_CI_CD/github_actions/hangman-e2e
    #     run: |
    #       npm ci
    #       npm run build --if-present
    #   - name: Upload dist folder artifact
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: dist_folder
    #       path: Module04_CI_CD/github_actions/hangman-front/dist
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: e2e tests
        uses: cypress-io/github-action@v6
        working-directory: ./Module04_CI_CD/github_actions/hangman-e2e
        with:
          project: ./Module04_CI_CD/github_actions/hangman-e2e

 