name: E2E

on:
  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: e2e tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./Module04_CI_CD/github_actions/hangman-e2e/e2e

 